version: '3.7'

services:
  cabinet:
    container_name: endterm-spring
    image: postgres:latest
    hostname: localhost
    ports:
      - 5438:5432
    env_file:
      - .env
    restart: unless-stopped